// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DecisionPendingToolCallStatus.
const (
	DecisionPendingToolCallStatusApproved  DecisionPendingToolCallStatus = "approved"
	DecisionPendingToolCallStatusDiscarded DecisionPendingToolCallStatus = "discarded"
	DecisionPendingToolCallStatusPending   DecisionPendingToolCallStatus = "pending"
	DecisionPendingToolCallStatusReplayed  DecisionPendingToolCallStatus = "replayed"
)

// Valid indicates whether the value is a known member of the DecisionPendingToolCallStatus enum.
func (e DecisionPendingToolCallStatus) Valid() bool {
	switch e {
	case DecisionPendingToolCallStatusApproved:
		return true
	case DecisionPendingToolCallStatusDiscarded:
		return true
	case DecisionPendingToolCallStatusPending:
		return true
	case DecisionPendingToolCallStatusReplayed:
		return true
	default:
		return false
	}
}

// Defines values for DecisionScopeType.
const (
	Draft     DecisionScopeType = "draft"
	Workspace DecisionScopeType = "workspace"
)

// Valid indicates whether the value is a known member of the DecisionScopeType enum.
func (e DecisionScopeType) Valid() bool {
	switch e {
	case Draft:
		return true
	case Workspace:
		return true
	default:
		return false
	}
}

// Defines values for DecisionStatus.
const (
	DecisionStatusAnswered  DecisionStatus = "answered"
	DecisionStatusCancelled DecisionStatus = "cancelled"
	DecisionStatusPending   DecisionStatus = "pending"
)

// Valid indicates whether the value is a known member of the DecisionStatus enum.
func (e DecisionStatus) Valid() bool {
	switch e {
	case DecisionStatusAnswered:
		return true
	case DecisionStatusCancelled:
		return true
	case DecisionStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DecisionType.
const (
	ApproveContentPlan DecisionType = "approve_content_plan"
	ApproveRoughCut    DecisionType = "approve_rough_cut"
	ApproveSpeechCut   DecisionType = "approve_speech_cut"
	AudioMode          DecisionType = "audio_mode"
	Bgm                DecisionType = "bgm"
	Export             DecisionType = "export"
	Generic            DecisionType = "generic"
	MemoryScope        DecisionType = "memory_scope"
	Subtitle           DecisionType = "subtitle"
	UrlImport          DecisionType = "url_import"
)

// Valid indicates whether the value is a known member of the DecisionType enum.
func (e DecisionType) Valid() bool {
	switch e {
	case ApproveContentPlan:
		return true
	case ApproveRoughCut:
		return true
	case ApproveSpeechCut:
		return true
	case AudioMode:
		return true
	case Bgm:
		return true
	case Export:
		return true
	case Generic:
		return true
	case MemoryScope:
		return true
	case Subtitle:
		return true
	case UrlImport:
		return true
	default:
		return false
	}
}

// Defines values for DecisionAnswerAnsweredVia.
const (
	Button          DecisionAnswerAnsweredVia = "button"
	NaturalLanguage DecisionAnswerAnsweredVia = "natural_language"
)

// Valid indicates whether the value is a known member of the DecisionAnswerAnsweredVia enum.
func (e DecisionAnswerAnsweredVia) Valid() bool {
	switch e {
	case Button:
		return true
	case NaturalLanguage:
		return true
	default:
		return false
	}
}

// Defines values for DecisionAnswerResponseStatus.
const (
	Answered DecisionAnswerResponseStatus = "answered"
)

// Valid indicates whether the value is a known member of the DecisionAnswerResponseStatus enum.
func (e DecisionAnswerResponseStatus) Valid() bool {
	switch e {
	case Answered:
		return true
	default:
		return false
	}
}

// Defines values for FsListEntryType.
const (
	Directory FsListEntryType = "directory"
	File      FsListEntryType = "file"
)

// Valid indicates whether the value is a known member of the FsListEntryType enum.
func (e FsListEntryType) Valid() bool {
	switch e {
	case Directory:
		return true
	case File:
		return true
	default:
		return false
	}
}

// Defines values for FsPickRequestMode.
const (
	Files  FsPickRequestMode = "files"
	Folder FsPickRequestMode = "folder"
)

// Valid indicates whether the value is a known member of the FsPickRequestMode enum.
func (e FsPickRequestMode) Valid() bool {
	switch e {
	case Files:
		return true
	case Folder:
		return true
	default:
		return false
	}
}

// Defines values for JobCancelResponseStatus.
const (
	Cancelled JobCancelResponseStatus = "cancelled"
)

// Valid indicates whether the value is a known member of the JobCancelResponseStatus enum.
func (e JobCancelResponseStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	default:
		return false
	}
}

// Defines values for MessageQueuedResponseKind.
const (
	UserMessage MessageQueuedResponseKind = "user_message"
)

// Valid indicates whether the value is a known member of the MessageQueuedResponseKind enum.
func (e MessageQueuedResponseKind) Valid() bool {
	switch e {
	case UserMessage:
		return true
	default:
		return false
	}
}

// Defines values for MessageQueuedResponseStatus.
const (
	Queued MessageQueuedResponseStatus = "queued"
)

// Valid indicates whether the value is a known member of the MessageQueuedResponseStatus enum.
func (e MessageQueuedResponseStatus) Valid() bool {
	switch e {
	case Queued:
		return true
	default:
		return false
	}
}

// Defines values for SecurityReason.
const (
	BadContentType SecurityReason = "bad_content_type"
	BadToken       SecurityReason = "bad_token"
	HostMismatch   SecurityReason = "host_mismatch"
	MissingToken   SecurityReason = "missing_token"
	OriginMismatch SecurityReason = "origin_mismatch"
	PathEscape     SecurityReason = "path_escape"
)

// Valid indicates whether the value is a known member of the SecurityReason enum.
func (e SecurityReason) Valid() bool {
	switch e {
	case BadContentType:
		return true
	case BadToken:
		return true
	case HostMismatch:
		return true
	case MissingToken:
		return true
	case OriginMismatch:
		return true
	case PathEscape:
		return true
	default:
		return false
	}
}

// Defines values for SecurityRefusalResponseError.
const (
	SecurityRefusal SecurityRefusalResponseError = "SecurityRefusal"
)

// Valid indicates whether the value is a known member of the SecurityRefusalResponseError enum.
func (e SecurityRefusalResponseError) Valid() bool {
	switch e {
	case SecurityRefusal:
		return true
	default:
		return false
	}
}

// Defines values for StorageMode.
const (
	Copy      StorageMode = "copy"
	Reference StorageMode = "reference"
)

// Valid indicates whether the value is a known member of the StorageMode enum.
func (e StorageMode) Valid() bool {
	switch e {
	case Copy:
		return true
	case Reference:
		return true
	default:
		return false
	}
}

// Defines values for TurnCancelResponseStatus.
const (
	Idle      TurnCancelResponseStatus = "idle"
	Requested TurnCancelResponseStatus = "requested"
)

// Valid indicates whether the value is a known member of the TurnCancelResponseStatus enum.
func (e TurnCancelResponseStatus) Valid() bool {
	switch e {
	case Idle:
		return true
	case Requested:
		return true
	default:
		return false
	}
}

// AssetJobSummary defines model for AssetJobSummary.
type AssetJobSummary struct {
	ErrorJson *map[string]interface{} `json:"error_json,omitempty"`
	JobId     string                  `json:"job_id"`
	Kind      string                  `json:"kind"`
	Progress  *float32                `json:"progress,omitempty"`
	Status    string                  `json:"status"`
}

// ConfirmRequest defines model for ConfirmRequest.
type ConfirmRequest struct {
	Confirm *bool `json:"confirm,omitempty"`
}

// CostSummary defines model for CostSummary.
type CostSummary struct {
	ByCapability      map[string]float32 `json:"by_capability"`
	ByProvider        map[string]float32 `json:"by_provider"`
	ProviderCallCount int                `json:"provider_call_count"`
	TotalCostEstimate float32            `json:"total_cost_estimate"`
}

// CurrentDecisionResponse defines model for CurrentDecisionResponse.
type CurrentDecisionResponse struct {
	Decision Decision `json:"decision"`
}

// Decision defines model for Decision.
type Decision struct {
	AllowFreeText         *bool                          `json:"allow_free_text,omitempty"`
	Answer                *DecisionAnswer                `json:"answer,omitempty"`
	Blocking              *bool                          `json:"blocking,omitempty"`
	ConsumedAt            *string                        `json:"consumed_at,omitempty"`
	CreatedByToolCallId   *string                        `json:"created_by_tool_call_id,omitempty"`
	DecisionId            string                         `json:"decision_id"`
	DraftId               *string                        `json:"draft_id,omitempty"`
	Options               *[]DecisionOption              `json:"options,omitempty"`
	PendingToolCall       *PendingToolCall               `json:"pending_tool_call,omitempty"`
	PendingToolCallStatus *DecisionPendingToolCallStatus `json:"pending_tool_call_status,omitempty"`
	Question              string                         `json:"question"`
	ReplayedToolCallId    *string                        `json:"replayed_tool_call_id,omitempty"`
	ScopeType             DecisionScopeType              `json:"scope_type"`
	Status                *DecisionStatus                `json:"status,omitempty"`
	Type                  DecisionType                   `json:"type"`
}

// DecisionPendingToolCallStatus defines model for Decision.PendingToolCallStatus.
type DecisionPendingToolCallStatus string

// DecisionScopeType defines model for Decision.ScopeType.
type DecisionScopeType string

// DecisionStatus defines model for Decision.Status.
type DecisionStatus string

// DecisionType defines model for Decision.Type.
type DecisionType string

// DecisionAnswer defines model for DecisionAnswer.
type DecisionAnswer struct {
	AnsweredVia DecisionAnswerAnsweredVia `json:"answered_via"`
	FreeText    *string                   `json:"free_text,omitempty"`
	OptionId    *string                   `json:"option_id,omitempty"`
	Payload     *map[string]interface{}   `json:"payload,omitempty"`
}

// DecisionAnswerAnsweredVia defines model for DecisionAnswer.AnsweredVia.
type DecisionAnswerAnsweredVia string

// DecisionAnswerRequest defines model for DecisionAnswerRequest.
type DecisionAnswerRequest struct {
	Answer  DecisionAnswer `json:"answer"`
	DraftId *string        `json:"draft_id,omitempty"`
}

// DecisionAnswerResponse defines model for DecisionAnswerResponse.
type DecisionAnswerResponse struct {
	DecisionId      string                       `json:"decision_id"`
	EventIds        []int                        `json:"event_ids"`
	ReplaysEnqueued int                          `json:"replays_enqueued"`
	Status          DecisionAnswerResponseStatus `json:"status"`
}

// DecisionAnswerResponseStatus defines model for DecisionAnswerResponse.Status.
type DecisionAnswerResponseStatus string

// DecisionOption defines model for DecisionOption.
type DecisionOption struct {
	Description *string                 `json:"description,omitempty"`
	Label       string                  `json:"label"`
	OptionId    string                  `json:"option_id"`
	Payload     *map[string]interface{} `json:"payload,omitempty"`
}

// DraftCopyRequest defines model for DraftCopyRequest.
type DraftCopyRequest struct {
	DraftId *string `json:"draft_id,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// DraftCostsResponse defines model for DraftCostsResponse.
type DraftCostsResponse struct {
	Costs   CostSummary `json:"costs"`
	DraftId string      `json:"draft_id"`
}

// DraftCreateRequest defines model for DraftCreateRequest.
type DraftCreateRequest struct {
	Brief    *map[string]interface{} `json:"brief,omitempty"`
	Defaults *map[string]interface{} `json:"defaults,omitempty"`
	DraftId  *string                 `json:"draft_id,omitempty"`
	Goal     *string                 `json:"goal,omitempty"`
	Name     *string                 `json:"name,omitempty"`
}

// DraftListItem defines model for DraftListItem.
type DraftListItem struct {
	CoverAssetIds []string `json:"cover_asset_ids"`
	DraftId       string   `json:"draft_id"`
	MaterialCount int      `json:"material_count"`
	Name          string   `json:"name"`
	Status        string   `json:"status"`
	UpdatedAt     string   `json:"updated_at"`
}

// DraftListResponse defines model for DraftListResponse.
type DraftListResponse struct {
	Drafts []DraftListItem `json:"drafts"`
}

// DraftMutationResponse defines model for DraftMutationResponse.
type DraftMutationResponse struct {
	Draft    DraftRecord `json:"draft"`
	EventIds []int       `json:"event_ids"`
}

// DraftRecord defines model for DraftRecord.
type DraftRecord struct {
	AudioPlan               *map[string]interface{}  `json:"audio_plan"`
	Brief                   map[string]interface{}   `json:"brief"`
	ContentPlan             *map[string]interface{}  `json:"content_plan"`
	CreatedAt               string                   `json:"created_at"`
	CutPlan                 *map[string]interface{}  `json:"cut_plan"`
	Defaults                map[string]interface{}   `json:"defaults"`
	DraftId                 string                   `json:"draft_id"`
	ExportCurrentId         *string                  `json:"export_current_id"`
	LastError               *map[string]interface{}  `json:"last_error"`
	LastViewedPreviewId     *string                  `json:"last_viewed_preview_id"`
	MessagesTailRef         *string                  `json:"messages_tail_ref"`
	Name                    string                   `json:"name"`
	PendingDecisionId       *string                  `json:"pending_decision_id"`
	PostprocessPlan         *map[string]interface{}  `json:"postprocess_plan"`
	PreviewCurrentId        *string                  `json:"preview_current_id"`
	RoughCutApproved        bool                     `json:"rough_cut_approved"`
	RoughCutApprovedVersion *int                     `json:"rough_cut_approved_version"`
	RunningJobs             []map[string]interface{} `json:"running_jobs"`
	ScratchMemory           map[string]interface{}   `json:"scratch_memory"`
	StateVersion            int                      `json:"state_version"`
	Status                  string                   `json:"status"`
	TimelineCurrentVersion  *int                     `json:"timeline_current_version"`
	TimelineValidated       bool                     `json:"timeline_validated"`
	UpdatedAt               string                   `json:"updated_at"`
}

// DraftResponse defines model for DraftResponse.
type DraftResponse struct {
	Draft DraftRecord `json:"draft"`
}

// DraftTimelineResponse defines model for DraftTimelineResponse.
type DraftTimelineResponse struct {
	DraftId         string                 `json:"draft_id"`
	LatestVersion   int                    `json:"latest_version"`
	ParentVersion   *int                   `json:"parent_version"`
	PreviewId       *string                `json:"preview_id"`
	RedoVersion     *int                   `json:"redo_version"`
	Summary         string                 `json:"summary"`
	Timeline        map[string]interface{} `json:"timeline"`
	TimelineVersion int                    `json:"timeline_version"`
}

// DraftUpdateRequest defines model for DraftUpdateRequest.
type DraftUpdateRequest struct {
	Name string `json:"name"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Conflict *ReducerConflictDetail `json:"conflict,omitempty"`
	Reason   string                 `json:"reason"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Detail ErrorDetail `json:"detail"`
}

// FsListEntry defines model for FsListEntry.
type FsListEntry struct {
	Extension *string         `json:"extension,omitempty"`
	Name      string          `json:"name"`
	Path      string          `json:"path"`
	Size      *int            `json:"size,omitempty"`
	Type      FsListEntryType `json:"type"`
}

// FsListEntryType defines model for FsListEntry.Type.
type FsListEntryType string

// FsListResponse defines model for FsListResponse.
type FsListResponse struct {
	Entries []FsListEntry `json:"entries"`
	Path    string        `json:"path"`
}

// FsPickRequest defines model for FsPickRequest.
type FsPickRequest struct {
	Mode *FsPickRequestMode `json:"mode,omitempty"`
}

// FsPickRequestMode defines model for FsPickRequest.Mode.
type FsPickRequestMode string

// FsPickResponse defines model for FsPickResponse.
type FsPickResponse struct {
	Available bool      `json:"available"`
	Paths     *[]string `json:"paths,omitempty"`
}

// FsRoot defines model for FsRoot.
type FsRoot struct {
	Exists bool   `json:"exists"`
	Name   string `json:"name"`
	Path   string `json:"path"`
}

// FsRootsResponse defines model for FsRootsResponse.
type FsRootsResponse struct {
	Roots []FsRoot `json:"roots"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// JobCancelRequest defines model for JobCancelRequest.
type JobCancelRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// JobCancelResponse defines model for JobCancelResponse.
type JobCancelResponse struct {
	EventIds []int                   `json:"event_ids"`
	JobId    string                  `json:"job_id"`
	Status   JobCancelResponseStatus `json:"status"`
}

// JobCancelResponseStatus defines model for JobCancelResponse.Status.
type JobCancelResponseStatus string

// MaterialAsset defines model for MaterialAsset.
type MaterialAsset struct {
	AssetId             string                  `json:"asset_id"`
	DurationSec         *float32                `json:"duration_sec"`
	Failure             *map[string]interface{} `json:"failure"`
	Filename            string                  `json:"filename"`
	Hash                string                  `json:"hash"`
	IngestStatus        string                  `json:"ingest_status"`
	Invalid             bool                    `json:"invalid"`
	Jobs                []AssetJobSummary       `json:"jobs"`
	Kind                string                  `json:"kind"`
	Mtime               *int                    `json:"mtime"`
	Probe               *map[string]interface{} `json:"probe"`
	ProxyObjectHash     *string                 `json:"proxy_object_hash"`
	ProxyReady          bool                    `json:"proxy_ready"`
	RelDir              *string                 `json:"rel_dir,omitempty"`
	Size                int                     `json:"size"`
	Source              string                  `json:"source"`
	StorageMode         string                  `json:"storage_mode"`
	ThumbnailReady      bool                    `json:"thumbnail_ready"`
	UnderstandingStatus string                  `json:"understanding_status"`
	Usable              bool                    `json:"usable"`
}

// MaterialImportLocalRequest defines model for MaterialImportLocalRequest.
type MaterialImportLocalRequest struct {
	AssetId     *string      `json:"asset_id,omitempty"`
	Path        *string      `json:"path,omitempty"`
	Paths       *[]string    `json:"paths,omitempty"`
	StorageMode *StorageMode `json:"storage_mode,omitempty"`
}

// MaterialMutationResponse defines model for MaterialMutationResponse.
type MaterialMutationResponse struct {
	AssetId    *string   `json:"asset_id,omitempty"`
	AssetIds   *[]string `json:"asset_ids,omitempty"`
	DecisionId *string   `json:"decision_id,omitempty"`
	DraftId    string    `json:"draft_id"`
	Duplicates *[]string `json:"duplicates,omitempty"`
	EventIds   []int     `json:"event_ids"`
	Failed     *[]string `json:"failed,omitempty"`
	JobId      *string   `json:"job_id,omitempty"`
	Skipped    *[]string `json:"skipped,omitempty"`
}

// MaterialSummaryResponse defines model for MaterialSummaryResponse.
type MaterialSummaryResponse struct {
	AssetId string                 `json:"asset_id"`
	Summary map[string]interface{} `json:"summary"`
}

// MaterialsResponse defines model for MaterialsResponse.
type MaterialsResponse struct {
	Assets              []MaterialAsset `json:"assets"`
	DraftId             string          `json:"draft_id"`
	InvalidatedAssetIds *[]string       `json:"invalidated_asset_ids,omitempty"`
}

// MessageCreateRequest defines model for MessageCreateRequest.
type MessageCreateRequest struct {
	Content   string  `json:"content"`
	MessageId *string `json:"message_id,omitempty"`
}

// MessageQueuedResponse defines model for MessageQueuedResponse.
type MessageQueuedResponse struct {
	DraftId   string                      `json:"draft_id"`
	Kind      MessageQueuedResponseKind   `json:"kind"`
	MessageId string                      `json:"message_id"`
	Status    MessageQueuedResponseStatus `json:"status"`
}

// MessageQueuedResponseKind defines model for MessageQueuedResponse.Kind.
type MessageQueuedResponseKind string

// MessageQueuedResponseStatus defines model for MessageQueuedResponse.Status.
type MessageQueuedResponseStatus string

// MessageRecord defines model for MessageRecord.
type MessageRecord struct {
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	Kind      string `json:"kind"`
	MessageId string `json:"message_id"`
	Role      string `json:"role"`
}

// MessagesResponse defines model for MessagesResponse.
type MessagesResponse struct {
	DraftId  string          `json:"draft_id"`
	Messages []MessageRecord `json:"messages"`
}

// PendingDecisionsResponse defines model for PendingDecisionsResponse.
type PendingDecisionsResponse struct {
	Decisions []Decision `json:"decisions"`
	DraftId   string     `json:"draft_id"`
}

// PendingToolCall defines model for PendingToolCall.
type PendingToolCall struct {
	ArgumentFingerprint string                 `json:"argument_fingerprint"`
	Arguments           map[string]interface{} `json:"arguments"`
	IdempotencyKey      string                 `json:"idempotency_key"`
	OriginalToolCallId  *string                `json:"original_tool_call_id,omitempty"`
	ToolName            string                 `json:"tool_name"`
}

// ReducerConflictDetail defines model for ReducerConflictDetail.
type ReducerConflictDetail struct {
	ActualStateVersion  int    `json:"actual_state_version"`
	DraftId             string `json:"draft_id"`
	EventType           string `json:"event_type"`
	ExpectedBaseVersion *int   `json:"expected_base_version"`
}

// SecurityReason defines model for SecurityReason.
type SecurityReason string

// SecurityRefusalResponse defines model for SecurityRefusalResponse.
type SecurityRefusalResponse struct {
	Error  SecurityRefusalResponseError `json:"error"`
	Reason SecurityReason               `json:"reason"`
}

// SecurityRefusalResponseError defines model for SecurityRefusalResponse.Error.
type SecurityRefusalResponseError string

// StorageMode defines model for StorageMode.
type StorageMode string

// TimelinePatchRequest defines model for TimelinePatchRequest.
type TimelinePatchRequest struct {
	Op map[string]interface{} `json:"op"`
}

// TimelineRestoreRequest defines model for TimelineRestoreRequest.
type TimelineRestoreRequest struct {
	Version int `json:"version"`
}

// TurnCancelResponse defines model for TurnCancelResponse.
type TurnCancelResponse struct {
	DraftId   string                   `json:"draft_id"`
	Requested bool                     `json:"requested"`
	Status    TurnCancelResponseStatus `json:"status"`
}

// TurnCancelResponseStatus defines model for TurnCancelResponse.Status.
type TurnCancelResponseStatus string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody defines parameters for ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost.
type ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody struct {
	union json.RawMessage
}

// ListDraftMessagesApiDraftsDraftIdMessagesGetParams defines parameters for ListDraftMessagesApiDraftsDraftIdMessagesGet.
type ListDraftMessagesApiDraftsDraftIdMessagesGetParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetDraftTimelineApiDraftsDraftIdTimelineGetParams defines parameters for GetDraftTimelineApiDraftsDraftIdTimelineGet.
type GetDraftTimelineApiDraftsDraftIdTimelineGetParams struct {
	Version *int `form:"version,omitempty" json:"version,omitempty"`
}

// FsListApiFsListGetParams defines parameters for FsListApiFsListGet.
type FsListApiFsListGetParams struct {
	Path string `form:"path" json:"path"`
}

// FsListApiFsListGet403JSONResponseBody defines parameters for FsListApiFsListGet.
type FsListApiFsListGet403JSONResponseBody struct {
	union json.RawMessage
}

// AnswerDecisionApiDecisionsDecisionIdAnswerPostJSONRequestBody defines body for AnswerDecisionApiDecisionsDecisionIdAnswerPost for application/json ContentType.
type AnswerDecisionApiDecisionsDecisionIdAnswerPostJSONRequestBody = DecisionAnswerRequest

// CreateDraftApiDraftsPostJSONRequestBody defines body for CreateDraftApiDraftsPost for application/json ContentType.
type CreateDraftApiDraftsPostJSONRequestBody = DraftCreateRequest

// DeleteDraftApiDraftsDraftIdDeleteJSONRequestBody defines body for DeleteDraftApiDraftsDraftIdDelete for application/json ContentType.
type DeleteDraftApiDraftsDraftIdDeleteJSONRequestBody = ConfirmRequest

// RenameDraftApiDraftsDraftIdPatchJSONRequestBody defines body for RenameDraftApiDraftsDraftIdPatch for application/json ContentType.
type RenameDraftApiDraftsDraftIdPatchJSONRequestBody = DraftUpdateRequest

// CopyDraftApiDraftsDraftIdCopyPostJSONRequestBody defines body for CopyDraftApiDraftsDraftIdCopyPost for application/json ContentType.
type CopyDraftApiDraftsDraftIdCopyPostJSONRequestBody = DraftCopyRequest

// ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPostJSONRequestBody defines body for ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost for application/json ContentType.
type ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPostJSONRequestBody = MaterialImportLocalRequest

// EnqueueMessageApiDraftsDraftIdMessagesPostJSONRequestBody defines body for EnqueueMessageApiDraftsDraftIdMessagesPost for application/json ContentType.
type EnqueueMessageApiDraftsDraftIdMessagesPostJSONRequestBody = MessageCreateRequest

// ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPostJSONRequestBody defines body for ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPost for application/json ContentType.
type ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPostJSONRequestBody = TimelinePatchRequest

// RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePostJSONRequestBody defines body for RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePost for application/json ContentType.
type RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePostJSONRequestBody = TimelineRestoreRequest

// FsPickApiFsPickPostJSONRequestBody defines body for FsPickApiFsPickPost for application/json ContentType.
type FsPickApiFsPickPostJSONRequestBody = FsPickRequest

// CancelJobApiJobsJobIdCancelPostJSONRequestBody defines body for CancelJobApiJobsJobIdCancelPost for application/json ContentType.
type CancelJobApiJobsJobIdCancelPostJSONRequestBody = JobCancelRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSecurityRefusalResponse returns the union data inside the ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody as a SecurityRefusalResponse
func (t ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) AsSecurityRefusalResponse() (SecurityRefusalResponse, error) {
	var body SecurityRefusalResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSecurityRefusalResponse overwrites any union data inside the ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody as the provided SecurityRefusalResponse
func (t *ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) FromSecurityRefusalResponse(v SecurityRefusalResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSecurityRefusalResponse performs a merge with any union data inside the ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody, using the provided SecurityRefusalResponse
func (t *ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) MergeSecurityRefusalResponse(v SecurityRefusalResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody as a ErrorResponse
func (t ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody as the provided ErrorResponse
func (t *ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody, using the provided ErrorResponse
func (t *ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost403JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSecurityRefusalResponse returns the union data inside the FsListApiFsListGet403JSONResponseBody as a SecurityRefusalResponse
func (t FsListApiFsListGet403JSONResponseBody) AsSecurityRefusalResponse() (SecurityRefusalResponse, error) {
	var body SecurityRefusalResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSecurityRefusalResponse overwrites any union data inside the FsListApiFsListGet403JSONResponseBody as the provided SecurityRefusalResponse
func (t *FsListApiFsListGet403JSONResponseBody) FromSecurityRefusalResponse(v SecurityRefusalResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSecurityRefusalResponse performs a merge with any union data inside the FsListApiFsListGet403JSONResponseBody, using the provided SecurityRefusalResponse
func (t *FsListApiFsListGet403JSONResponseBody) MergeSecurityRefusalResponse(v SecurityRefusalResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the FsListApiFsListGet403JSONResponseBody as a ErrorResponse
func (t FsListApiFsListGet403JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the FsListApiFsListGet403JSONResponseBody as the provided ErrorResponse
func (t *FsListApiFsListGet403JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the FsListApiFsListGet403JSONResponseBody, using the provided ErrorResponse
func (t *FsListApiFsListGet403JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FsListApiFsListGet403JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FsListApiFsListGet403JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Answer Decision
	// (POST /api/decisions/{decision_id}/answer)
	AnswerDecisionApiDecisionsDecisionIdAnswerPost(w http.ResponseWriter, r *http.Request, decisionId string)
	// List Drafts
	// (GET /api/drafts)
	ListDraftsApiDraftsGet(w http.ResponseWriter, r *http.Request)
	// Create Draft
	// (POST /api/drafts)
	CreateDraftApiDraftsPost(w http.ResponseWriter, r *http.Request)
	// Delete Draft
	// (DELETE /api/drafts/{draft_id})
	DeleteDraftApiDraftsDraftIdDelete(w http.ResponseWriter, r *http.Request, draftId string)
	// Get Draft
	// (GET /api/drafts/{draft_id})
	GetDraftApiDraftsDraftIdGet(w http.ResponseWriter, r *http.Request, draftId string)
	// Rename Draft
	// (PATCH /api/drafts/{draft_id})
	RenameDraftApiDraftsDraftIdPatch(w http.ResponseWriter, r *http.Request, draftId string)
	// Copy Draft
	// (POST /api/drafts/{draft_id}/copy)
	CopyDraftApiDraftsDraftIdCopyPost(w http.ResponseWriter, r *http.Request, draftId string)
	// Draft Costs
	// (GET /api/drafts/{draft_id}/costs)
	DraftCostsApiDraftsDraftIdCostsGet(w http.ResponseWriter, r *http.Request, draftId string)
	// Current Decision
	// (GET /api/drafts/{draft_id}/decisions/current)
	CurrentDecisionApiDraftsDraftIdDecisionsCurrentGet(w http.ResponseWriter, r *http.Request, draftId string)
	// Pending Draft Decisions
	// (GET /api/drafts/{draft_id}/decisions/pending)
	PendingDraftDecisionsApiDraftsDraftIdDecisionsPendingGet(w http.ResponseWriter, r *http.Request, draftId string)
	// Draft Events
	// (GET /api/drafts/{draft_id}/events)
	DraftEventsApiDraftsDraftIdEventsGet(w http.ResponseWriter, r *http.Request, draftId string)
	// List Materials
	// (GET /api/drafts/{draft_id}/materials)
	ListMaterialsApiDraftsDraftIdMaterialsGet(w http.ResponseWriter, r *http.Request, draftId string)
	// Import Local Material
	// (POST /api/drafts/{draft_id}/materials/import-local)
	ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost(w http.ResponseWriter, r *http.Request, draftId string)
	// Revalidate Materials
	// (POST /api/drafts/{draft_id}/materials/revalidate)
	RevalidateMaterialsApiDraftsDraftIdMaterialsRevalidatePost(w http.ResponseWriter, r *http.Request, draftId string)
	// Delete Material
	// (DELETE /api/drafts/{draft_id}/materials/{asset_id})
	DeleteMaterialApiDraftsDraftIdMaterialsAssetIdDelete(w http.ResponseWriter, r *http.Request, draftId string, assetId string)
	// Get Material Summary
	// (GET /api/drafts/{draft_id}/materials/{asset_id}/summary)
	GetMaterialSummaryApiDraftsDraftIdMaterialsAssetIdSummaryGet(w http.ResponseWriter, r *http.Request, draftId string, assetId string)
	// List Draft Messages
	// (GET /api/drafts/{draft_id}/messages)
	ListDraftMessagesApiDraftsDraftIdMessagesGet(w http.ResponseWriter, r *http.Request, draftId string, params ListDraftMessagesApiDraftsDraftIdMessagesGetParams)
	// Enqueue Message
	// (POST /api/drafts/{draft_id}/messages)
	EnqueueMessageApiDraftsDraftIdMessagesPost(w http.ResponseWriter, r *http.Request, draftId string)
	// Preview Viewed
	// (POST /api/drafts/{draft_id}/previews/{preview_id}/viewed)
	PreviewViewedApiDraftsDraftIdPreviewsPreviewIdViewedPost(w http.ResponseWriter, r *http.Request, draftId string, previewId string)
	// Get Draft Timeline
	// (GET /api/drafts/{draft_id}/timeline)
	GetDraftTimelineApiDraftsDraftIdTimelineGet(w http.ResponseWriter, r *http.Request, draftId string, params GetDraftTimelineApiDraftsDraftIdTimelineGetParams)
	// Apply Timeline Patch
	// (POST /api/drafts/{draft_id}/timeline/patch)
	ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPost(w http.ResponseWriter, r *http.Request, draftId string)
	// Restore Timeline Version
	// (POST /api/drafts/{draft_id}/timeline/restore)
	RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePost(w http.ResponseWriter, r *http.Request, draftId string)
	// Draft Turn Stream
	// (GET /api/drafts/{draft_id}/turn-stream)
	DraftTurnStreamApiDraftsDraftIdTurnStreamGet(w http.ResponseWriter, r *http.Request, draftId string)
	// Cancel Current Turn
	// (POST /api/drafts/{draft_id}/turn/cancel)
	CancelCurrentTurnApiDraftsDraftIdTurnCancelPost(w http.ResponseWriter, r *http.Request, draftId string)
	// Workspace Events
	// (GET /api/events)
	WorkspaceEventsApiEventsGet(w http.ResponseWriter, r *http.Request)
	// Fs List
	// (GET /api/fs/list)
	FsListApiFsListGet(w http.ResponseWriter, r *http.Request, params FsListApiFsListGetParams)
	// Fs Pick
	// (POST /api/fs/pick)
	FsPickApiFsPickPost(w http.ResponseWriter, r *http.Request)
	// Fs Roots
	// (GET /api/fs/roots)
	FsRootsApiFsRootsGet(w http.ResponseWriter, r *http.Request)
	// Cancel Job
	// (POST /api/jobs/{job_id}/cancel)
	CancelJobApiJobsJobIdCancelPost(w http.ResponseWriter, r *http.Request, jobId string)
	// Media Export
	// (GET /api/media/export/{export_id})
	MediaExportApiMediaExportExportIdGet(w http.ResponseWriter, r *http.Request, exportId string)
	// Media Export
	// (HEAD /api/media/export/{export_id})
	MediaExportApiMediaExportExportIdHead(w http.ResponseWriter, r *http.Request, exportId string)
	// Media Preview
	// (GET /api/media/preview/{preview_id})
	MediaPreviewApiMediaPreviewPreviewIdGet(w http.ResponseWriter, r *http.Request, previewId string)
	// Media Preview
	// (HEAD /api/media/preview/{preview_id})
	MediaPreviewApiMediaPreviewPreviewIdHead(w http.ResponseWriter, r *http.Request, previewId string)
	// Media Proxy
	// (GET /api/media/{asset_id}/proxy)
	MediaProxyApiMediaAssetIdProxyGet(w http.ResponseWriter, r *http.Request, assetId string)
	// Media Proxy
	// (HEAD /api/media/{asset_id}/proxy)
	MediaProxyApiMediaAssetIdProxyHead(w http.ResponseWriter, r *http.Request, assetId string)
	// Media Source
	// (GET /api/media/{asset_id}/source)
	MediaSourceApiMediaAssetIdSourceGet(w http.ResponseWriter, r *http.Request, assetId string)
	// Media Source
	// (HEAD /api/media/{asset_id}/source)
	MediaSourceApiMediaAssetIdSourceHead(w http.ResponseWriter, r *http.Request, assetId string)
	// Media Thumbnail
	// (GET /api/media/{asset_id}/thumbnail)
	MediaThumbnailApiMediaAssetIdThumbnailGet(w http.ResponseWriter, r *http.Request, assetId string)
	// Media Thumbnail
	// (HEAD /api/media/{asset_id}/thumbnail)
	MediaThumbnailApiMediaAssetIdThumbnailHead(w http.ResponseWriter, r *http.Request, assetId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Answer Decision
// (POST /api/decisions/{decision_id}/answer)
func (_ Unimplemented) AnswerDecisionApiDecisionsDecisionIdAnswerPost(w http.ResponseWriter, r *http.Request, decisionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Drafts
// (GET /api/drafts)
func (_ Unimplemented) ListDraftsApiDraftsGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Draft
// (POST /api/drafts)
func (_ Unimplemented) CreateDraftApiDraftsPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Draft
// (DELETE /api/drafts/{draft_id})
func (_ Unimplemented) DeleteDraftApiDraftsDraftIdDelete(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Draft
// (GET /api/drafts/{draft_id})
func (_ Unimplemented) GetDraftApiDraftsDraftIdGet(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename Draft
// (PATCH /api/drafts/{draft_id})
func (_ Unimplemented) RenameDraftApiDraftsDraftIdPatch(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Copy Draft
// (POST /api/drafts/{draft_id}/copy)
func (_ Unimplemented) CopyDraftApiDraftsDraftIdCopyPost(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Draft Costs
// (GET /api/drafts/{draft_id}/costs)
func (_ Unimplemented) DraftCostsApiDraftsDraftIdCostsGet(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Current Decision
// (GET /api/drafts/{draft_id}/decisions/current)
func (_ Unimplemented) CurrentDecisionApiDraftsDraftIdDecisionsCurrentGet(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Pending Draft Decisions
// (GET /api/drafts/{draft_id}/decisions/pending)
func (_ Unimplemented) PendingDraftDecisionsApiDraftsDraftIdDecisionsPendingGet(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Draft Events
// (GET /api/drafts/{draft_id}/events)
func (_ Unimplemented) DraftEventsApiDraftsDraftIdEventsGet(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Materials
// (GET /api/drafts/{draft_id}/materials)
func (_ Unimplemented) ListMaterialsApiDraftsDraftIdMaterialsGet(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Import Local Material
// (POST /api/drafts/{draft_id}/materials/import-local)
func (_ Unimplemented) ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revalidate Materials
// (POST /api/drafts/{draft_id}/materials/revalidate)
func (_ Unimplemented) RevalidateMaterialsApiDraftsDraftIdMaterialsRevalidatePost(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Material
// (DELETE /api/drafts/{draft_id}/materials/{asset_id})
func (_ Unimplemented) DeleteMaterialApiDraftsDraftIdMaterialsAssetIdDelete(w http.ResponseWriter, r *http.Request, draftId string, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Material Summary
// (GET /api/drafts/{draft_id}/materials/{asset_id}/summary)
func (_ Unimplemented) GetMaterialSummaryApiDraftsDraftIdMaterialsAssetIdSummaryGet(w http.ResponseWriter, r *http.Request, draftId string, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Draft Messages
// (GET /api/drafts/{draft_id}/messages)
func (_ Unimplemented) ListDraftMessagesApiDraftsDraftIdMessagesGet(w http.ResponseWriter, r *http.Request, draftId string, params ListDraftMessagesApiDraftsDraftIdMessagesGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Enqueue Message
// (POST /api/drafts/{draft_id}/messages)
func (_ Unimplemented) EnqueueMessageApiDraftsDraftIdMessagesPost(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Preview Viewed
// (POST /api/drafts/{draft_id}/previews/{preview_id}/viewed)
func (_ Unimplemented) PreviewViewedApiDraftsDraftIdPreviewsPreviewIdViewedPost(w http.ResponseWriter, r *http.Request, draftId string, previewId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Draft Timeline
// (GET /api/drafts/{draft_id}/timeline)
func (_ Unimplemented) GetDraftTimelineApiDraftsDraftIdTimelineGet(w http.ResponseWriter, r *http.Request, draftId string, params GetDraftTimelineApiDraftsDraftIdTimelineGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Apply Timeline Patch
// (POST /api/drafts/{draft_id}/timeline/patch)
func (_ Unimplemented) ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPost(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore Timeline Version
// (POST /api/drafts/{draft_id}/timeline/restore)
func (_ Unimplemented) RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePost(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Draft Turn Stream
// (GET /api/drafts/{draft_id}/turn-stream)
func (_ Unimplemented) DraftTurnStreamApiDraftsDraftIdTurnStreamGet(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel Current Turn
// (POST /api/drafts/{draft_id}/turn/cancel)
func (_ Unimplemented) CancelCurrentTurnApiDraftsDraftIdTurnCancelPost(w http.ResponseWriter, r *http.Request, draftId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Workspace Events
// (GET /api/events)
func (_ Unimplemented) WorkspaceEventsApiEventsGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fs List
// (GET /api/fs/list)
func (_ Unimplemented) FsListApiFsListGet(w http.ResponseWriter, r *http.Request, params FsListApiFsListGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fs Pick
// (POST /api/fs/pick)
func (_ Unimplemented) FsPickApiFsPickPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fs Roots
// (GET /api/fs/roots)
func (_ Unimplemented) FsRootsApiFsRootsGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel Job
// (POST /api/jobs/{job_id}/cancel)
func (_ Unimplemented) CancelJobApiJobsJobIdCancelPost(w http.ResponseWriter, r *http.Request, jobId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Export
// (GET /api/media/export/{export_id})
func (_ Unimplemented) MediaExportApiMediaExportExportIdGet(w http.ResponseWriter, r *http.Request, exportId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Export
// (HEAD /api/media/export/{export_id})
func (_ Unimplemented) MediaExportApiMediaExportExportIdHead(w http.ResponseWriter, r *http.Request, exportId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Preview
// (GET /api/media/preview/{preview_id})
func (_ Unimplemented) MediaPreviewApiMediaPreviewPreviewIdGet(w http.ResponseWriter, r *http.Request, previewId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Preview
// (HEAD /api/media/preview/{preview_id})
func (_ Unimplemented) MediaPreviewApiMediaPreviewPreviewIdHead(w http.ResponseWriter, r *http.Request, previewId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Proxy
// (GET /api/media/{asset_id}/proxy)
func (_ Unimplemented) MediaProxyApiMediaAssetIdProxyGet(w http.ResponseWriter, r *http.Request, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Proxy
// (HEAD /api/media/{asset_id}/proxy)
func (_ Unimplemented) MediaProxyApiMediaAssetIdProxyHead(w http.ResponseWriter, r *http.Request, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Source
// (GET /api/media/{asset_id}/source)
func (_ Unimplemented) MediaSourceApiMediaAssetIdSourceGet(w http.ResponseWriter, r *http.Request, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Source
// (HEAD /api/media/{asset_id}/source)
func (_ Unimplemented) MediaSourceApiMediaAssetIdSourceHead(w http.ResponseWriter, r *http.Request, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Thumbnail
// (GET /api/media/{asset_id}/thumbnail)
func (_ Unimplemented) MediaThumbnailApiMediaAssetIdThumbnailGet(w http.ResponseWriter, r *http.Request, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Media Thumbnail
// (HEAD /api/media/{asset_id}/thumbnail)
func (_ Unimplemented) MediaThumbnailApiMediaAssetIdThumbnailHead(w http.ResponseWriter, r *http.Request, assetId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AnswerDecisionApiDecisionsDecisionIdAnswerPost operation middleware
func (siw *ServerInterfaceWrapper) AnswerDecisionApiDecisionsDecisionIdAnswerPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "decision_id" -------------
	var decisionId string

	err = runtime.BindStyledParameterWithOptions("simple", "decision_id", chi.URLParam(r, "decision_id"), &decisionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "decision_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnswerDecisionApiDecisionsDecisionIdAnswerPost(w, r, decisionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDraftsApiDraftsGet operation middleware
func (siw *ServerInterfaceWrapper) ListDraftsApiDraftsGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDraftsApiDraftsGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDraftApiDraftsPost operation middleware
func (siw *ServerInterfaceWrapper) CreateDraftApiDraftsPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDraftApiDraftsPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDraftApiDraftsDraftIdDelete operation middleware
func (siw *ServerInterfaceWrapper) DeleteDraftApiDraftsDraftIdDelete(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDraftApiDraftsDraftIdDelete(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDraftApiDraftsDraftIdGet operation middleware
func (siw *ServerInterfaceWrapper) GetDraftApiDraftsDraftIdGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDraftApiDraftsDraftIdGet(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameDraftApiDraftsDraftIdPatch operation middleware
func (siw *ServerInterfaceWrapper) RenameDraftApiDraftsDraftIdPatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameDraftApiDraftsDraftIdPatch(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CopyDraftApiDraftsDraftIdCopyPost operation middleware
func (siw *ServerInterfaceWrapper) CopyDraftApiDraftsDraftIdCopyPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CopyDraftApiDraftsDraftIdCopyPost(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DraftCostsApiDraftsDraftIdCostsGet operation middleware
func (siw *ServerInterfaceWrapper) DraftCostsApiDraftsDraftIdCostsGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DraftCostsApiDraftsDraftIdCostsGet(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentDecisionApiDraftsDraftIdDecisionsCurrentGet operation middleware
func (siw *ServerInterfaceWrapper) CurrentDecisionApiDraftsDraftIdDecisionsCurrentGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentDecisionApiDraftsDraftIdDecisionsCurrentGet(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PendingDraftDecisionsApiDraftsDraftIdDecisionsPendingGet operation middleware
func (siw *ServerInterfaceWrapper) PendingDraftDecisionsApiDraftsDraftIdDecisionsPendingGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PendingDraftDecisionsApiDraftsDraftIdDecisionsPendingGet(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DraftEventsApiDraftsDraftIdEventsGet operation middleware
func (siw *ServerInterfaceWrapper) DraftEventsApiDraftsDraftIdEventsGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DraftEventsApiDraftsDraftIdEventsGet(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMaterialsApiDraftsDraftIdMaterialsGet operation middleware
func (siw *ServerInterfaceWrapper) ListMaterialsApiDraftsDraftIdMaterialsGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMaterialsApiDraftsDraftIdMaterialsGet(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost operation middleware
func (siw *ServerInterfaceWrapper) ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevalidateMaterialsApiDraftsDraftIdMaterialsRevalidatePost operation middleware
func (siw *ServerInterfaceWrapper) RevalidateMaterialsApiDraftsDraftIdMaterialsRevalidatePost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevalidateMaterialsApiDraftsDraftIdMaterialsRevalidatePost(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMaterialApiDraftsDraftIdMaterialsAssetIdDelete operation middleware
func (siw *ServerInterfaceWrapper) DeleteMaterialApiDraftsDraftIdMaterialsAssetIdDelete(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMaterialApiDraftsDraftIdMaterialsAssetIdDelete(w, r, draftId, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMaterialSummaryApiDraftsDraftIdMaterialsAssetIdSummaryGet operation middleware
func (siw *ServerInterfaceWrapper) GetMaterialSummaryApiDraftsDraftIdMaterialsAssetIdSummaryGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMaterialSummaryApiDraftsDraftIdMaterialsAssetIdSummaryGet(w, r, draftId, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDraftMessagesApiDraftsDraftIdMessagesGet operation middleware
func (siw *ServerInterfaceWrapper) ListDraftMessagesApiDraftsDraftIdMessagesGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDraftMessagesApiDraftsDraftIdMessagesGetParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDraftMessagesApiDraftsDraftIdMessagesGet(w, r, draftId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnqueueMessageApiDraftsDraftIdMessagesPost operation middleware
func (siw *ServerInterfaceWrapper) EnqueueMessageApiDraftsDraftIdMessagesPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnqueueMessageApiDraftsDraftIdMessagesPost(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewViewedApiDraftsDraftIdPreviewsPreviewIdViewedPost operation middleware
func (siw *ServerInterfaceWrapper) PreviewViewedApiDraftsDraftIdPreviewsPreviewIdViewedPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	// ------------- Path parameter "preview_id" -------------
	var previewId string

	err = runtime.BindStyledParameterWithOptions("simple", "preview_id", chi.URLParam(r, "preview_id"), &previewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preview_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewViewedApiDraftsDraftIdPreviewsPreviewIdViewedPost(w, r, draftId, previewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDraftTimelineApiDraftsDraftIdTimelineGet operation middleware
func (siw *ServerInterfaceWrapper) GetDraftTimelineApiDraftsDraftIdTimelineGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDraftTimelineApiDraftsDraftIdTimelineGetParams

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDraftTimelineApiDraftsDraftIdTimelineGet(w, r, draftId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPost operation middleware
func (siw *ServerInterfaceWrapper) ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPost(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePost operation middleware
func (siw *ServerInterfaceWrapper) RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePost(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DraftTurnStreamApiDraftsDraftIdTurnStreamGet operation middleware
func (siw *ServerInterfaceWrapper) DraftTurnStreamApiDraftsDraftIdTurnStreamGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DraftTurnStreamApiDraftsDraftIdTurnStreamGet(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelCurrentTurnApiDraftsDraftIdTurnCancelPost operation middleware
func (siw *ServerInterfaceWrapper) CancelCurrentTurnApiDraftsDraftIdTurnCancelPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "draft_id" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draft_id", chi.URLParam(r, "draft_id"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "draft_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelCurrentTurnApiDraftsDraftIdTurnCancelPost(w, r, draftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WorkspaceEventsApiEventsGet operation middleware
func (siw *ServerInterfaceWrapper) WorkspaceEventsApiEventsGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WorkspaceEventsApiEventsGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FsListApiFsListGet operation middleware
func (siw *ServerInterfaceWrapper) FsListApiFsListGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params FsListApiFsListGetParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FsListApiFsListGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FsPickApiFsPickPost operation middleware
func (siw *ServerInterfaceWrapper) FsPickApiFsPickPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FsPickApiFsPickPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FsRootsApiFsRootsGet operation middleware
func (siw *ServerInterfaceWrapper) FsRootsApiFsRootsGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FsRootsApiFsRootsGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelJobApiJobsJobIdCancelPost operation middleware
func (siw *ServerInterfaceWrapper) CancelJobApiJobsJobIdCancelPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelJobApiJobsJobIdCancelPost(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaExportApiMediaExportExportIdGet operation middleware
func (siw *ServerInterfaceWrapper) MediaExportApiMediaExportExportIdGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "export_id" -------------
	var exportId string

	err = runtime.BindStyledParameterWithOptions("simple", "export_id", chi.URLParam(r, "export_id"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "export_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaExportApiMediaExportExportIdGet(w, r, exportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaExportApiMediaExportExportIdHead operation middleware
func (siw *ServerInterfaceWrapper) MediaExportApiMediaExportExportIdHead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "export_id" -------------
	var exportId string

	err = runtime.BindStyledParameterWithOptions("simple", "export_id", chi.URLParam(r, "export_id"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "export_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaExportApiMediaExportExportIdHead(w, r, exportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaPreviewApiMediaPreviewPreviewIdGet operation middleware
func (siw *ServerInterfaceWrapper) MediaPreviewApiMediaPreviewPreviewIdGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "preview_id" -------------
	var previewId string

	err = runtime.BindStyledParameterWithOptions("simple", "preview_id", chi.URLParam(r, "preview_id"), &previewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preview_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaPreviewApiMediaPreviewPreviewIdGet(w, r, previewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaPreviewApiMediaPreviewPreviewIdHead operation middleware
func (siw *ServerInterfaceWrapper) MediaPreviewApiMediaPreviewPreviewIdHead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "preview_id" -------------
	var previewId string

	err = runtime.BindStyledParameterWithOptions("simple", "preview_id", chi.URLParam(r, "preview_id"), &previewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preview_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaPreviewApiMediaPreviewPreviewIdHead(w, r, previewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaProxyApiMediaAssetIdProxyGet operation middleware
func (siw *ServerInterfaceWrapper) MediaProxyApiMediaAssetIdProxyGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaProxyApiMediaAssetIdProxyGet(w, r, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaProxyApiMediaAssetIdProxyHead operation middleware
func (siw *ServerInterfaceWrapper) MediaProxyApiMediaAssetIdProxyHead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaProxyApiMediaAssetIdProxyHead(w, r, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaSourceApiMediaAssetIdSourceGet operation middleware
func (siw *ServerInterfaceWrapper) MediaSourceApiMediaAssetIdSourceGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaSourceApiMediaAssetIdSourceGet(w, r, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaSourceApiMediaAssetIdSourceHead operation middleware
func (siw *ServerInterfaceWrapper) MediaSourceApiMediaAssetIdSourceHead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaSourceApiMediaAssetIdSourceHead(w, r, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaThumbnailApiMediaAssetIdThumbnailGet operation middleware
func (siw *ServerInterfaceWrapper) MediaThumbnailApiMediaAssetIdThumbnailGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaThumbnailApiMediaAssetIdThumbnailGet(w, r, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MediaThumbnailApiMediaAssetIdThumbnailHead operation middleware
func (siw *ServerInterfaceWrapper) MediaThumbnailApiMediaAssetIdThumbnailHead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset_id" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "asset_id", chi.URLParam(r, "asset_id"), &assetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MediaThumbnailApiMediaAssetIdThumbnailHead(w, r, assetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/decisions/{decision_id}/answer", wrapper.AnswerDecisionApiDecisionsDecisionIdAnswerPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts", wrapper.ListDraftsApiDraftsGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts", wrapper.CreateDraftApiDraftsPost)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/drafts/{draft_id}", wrapper.DeleteDraftApiDraftsDraftIdDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}", wrapper.GetDraftApiDraftsDraftIdGet)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/drafts/{draft_id}", wrapper.RenameDraftApiDraftsDraftIdPatch)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/copy", wrapper.CopyDraftApiDraftsDraftIdCopyPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/costs", wrapper.DraftCostsApiDraftsDraftIdCostsGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/decisions/current", wrapper.CurrentDecisionApiDraftsDraftIdDecisionsCurrentGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/decisions/pending", wrapper.PendingDraftDecisionsApiDraftsDraftIdDecisionsPendingGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/events", wrapper.DraftEventsApiDraftsDraftIdEventsGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/materials", wrapper.ListMaterialsApiDraftsDraftIdMaterialsGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/materials/import-local", wrapper.ImportLocalMaterialApiDraftsDraftIdMaterialsImportLocalPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/materials/revalidate", wrapper.RevalidateMaterialsApiDraftsDraftIdMaterialsRevalidatePost)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/drafts/{draft_id}/materials/{asset_id}", wrapper.DeleteMaterialApiDraftsDraftIdMaterialsAssetIdDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/materials/{asset_id}/summary", wrapper.GetMaterialSummaryApiDraftsDraftIdMaterialsAssetIdSummaryGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/messages", wrapper.ListDraftMessagesApiDraftsDraftIdMessagesGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/messages", wrapper.EnqueueMessageApiDraftsDraftIdMessagesPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/previews/{preview_id}/viewed", wrapper.PreviewViewedApiDraftsDraftIdPreviewsPreviewIdViewedPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/timeline", wrapper.GetDraftTimelineApiDraftsDraftIdTimelineGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/timeline/patch", wrapper.ApplyTimelinePatchApiDraftsDraftIdTimelinePatchPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/timeline/restore", wrapper.RestoreTimelineVersionApiDraftsDraftIdTimelineRestorePost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/drafts/{draft_id}/turn-stream", wrapper.DraftTurnStreamApiDraftsDraftIdTurnStreamGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/drafts/{draft_id}/turn/cancel", wrapper.CancelCurrentTurnApiDraftsDraftIdTurnCancelPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/events", wrapper.WorkspaceEventsApiEventsGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/fs/list", wrapper.FsListApiFsListGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/fs/pick", wrapper.FsPickApiFsPickPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/fs/roots", wrapper.FsRootsApiFsRootsGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/jobs/{job_id}/cancel", wrapper.CancelJobApiJobsJobIdCancelPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/media/export/{export_id}", wrapper.MediaExportApiMediaExportExportIdGet)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/media/export/{export_id}", wrapper.MediaExportApiMediaExportExportIdHead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/media/preview/{preview_id}", wrapper.MediaPreviewApiMediaPreviewPreviewIdGet)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/media/preview/{preview_id}", wrapper.MediaPreviewApiMediaPreviewPreviewIdHead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/media/{asset_id}/proxy", wrapper.MediaProxyApiMediaAssetIdProxyGet)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/media/{asset_id}/proxy", wrapper.MediaProxyApiMediaAssetIdProxyHead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/media/{asset_id}/source", wrapper.MediaSourceApiMediaAssetIdSourceGet)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/media/{asset_id}/source", wrapper.MediaSourceApiMediaAssetIdSourceHead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/media/{asset_id}/thumbnail", wrapper.MediaThumbnailApiMediaAssetIdThumbnailGet)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/media/{asset_id}/thumbnail", wrapper.MediaThumbnailApiMediaAssetIdThumbnailHead)
	})

	return r
}
