package agentexec

import (
	"context"
	"sync"

	"github.com/nanzhi84/Rushes/go/internal/timeline"
	rushestools "github.com/nanzhi84/Rushes/go/internal/tools"
)

type atomicEditAdmissionContextKey struct{}

type atomicEditAdmissionState struct {
	mu      sync.Mutex
	byDraft map[string]*atomicEditAdmissionDraft
}

type atomicEditAdmissionDraft struct {
	initialClipIDs     map[string]struct{}
	coordinatesChanged bool
}

type atomicEditAdmissionDecision string

const (
	atomicEditAdmitted                     atomicEditAdmissionDecision = ""
	atomicEditNewClipTarget                atomicEditAdmissionDecision = "new_clip_target"
	atomicEditUnobservedTimelineCoordinate atomicEditAdmissionDecision = "unobserved_timeline_coordinate"
)

// WithAtomicEditAdmission starts one admission scope for a single assistant
// tool-call message. Stable clip IDs and source ranges may compose inside the
// message. An edit may not consume an ID generated by an earlier call, nor may
// it consume timeline-frame coordinates after an earlier call changed that
// coordinate space.
func WithAtomicEditAdmission(ctx context.Context) context.Context {
	return context.WithValue(ctx, atomicEditAdmissionContextKey{}, &atomicEditAdmissionState{
		byDraft: map[string]*atomicEditAdmissionDraft{},
	})
}

func atomicEditAdmissionFromContext(ctx context.Context) *atomicEditAdmissionState {
	state, _ := ctx.Value(atomicEditAdmissionContextKey{}).(*atomicEditAdmissionState)
	return state
}

func (state *atomicEditAdmissionState) admit(
	draftID string,
	document timeline.Document,
	operation map[string]any,
) atomicEditAdmissionDecision {
	if state == nil {
		return atomicEditAdmitted
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	draft, initialized := state.byDraft[draftID]
	if !initialized {
		initial := make(map[string]struct{})
		for _, track := range document.Tracks {
			for _, clip := range track.Clips {
				if clip.TimelineClipID != "" {
					initial[clip.TimelineClipID] = struct{}{}
				}
			}
		}
		draft = &atomicEditAdmissionDraft{initialClipIDs: initial}
		state.byDraft[draftID] = draft
	}
	targetClipID, _ := operation["timeline_clip_id"].(string)
	if targetClipID != "" {
		if _, existed := draft.initialClipIDs[targetClipID]; !existed {
			return atomicEditNewClipTarget
		}
	}
	if draft.coordinatesChanged && usesTimelineCoordinates(operation) {
		return atomicEditUnobservedTimelineCoordinate
	}
	return atomicEditAdmitted
}

// recordSuccess commits only facts established by a successful persisted edit.
// The tool router serializes every message containing writes, so a later call
// observes this flag after the earlier call returns. Failed edits leave the
// message-start coordinate space usable by independent later calls.
func (state *atomicEditAdmissionState) recordSuccess(
	draftID string,
	operation map[string]any,
) {
	if state == nil || !changesTimelineCoordinates(operation) {
		return
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	if draft := state.byDraft[draftID]; draft != nil {
		draft.coordinatesChanged = true
	}
}

func usesTimelineCoordinates(operation map[string]any) bool {
	switch operation["kind"] {
	case "insert_clip":
		trackID := ValueOr(StringValue(operation["track_id"]), "visual_base")
		return trackID != "visual_base"
	case "insert_subtitle", "delete_range",
		"split_clip", "reorder_clip", "move_clip", "trim_clip_edge":
		return true
	default:
		return false
	}
}

func changesTimelineCoordinates(operation map[string]any) bool {
	switch operation["kind"] {
	case "trim_clip", "split_clip", "reorder_clip", "move_clip",
		"trim_clip_edge", "delete_clip", "delete_range",
		"delete_source_range", "insert_clip", "set_playback_rate":
		return true
	default:
		return false
	}
}

func atomicEditAdmissionFailure(
	decision atomicEditAdmissionDecision,
	targetClipID string,
) rushestools.ToolResult {
	observation := "本条 assistant 消息开始时不存在该 timeline_clip_id，不能依赖同消息内新生成或猜测的 ID。"
	recovery := "等待当前工具消息全部返回；下一次 provider 调用读取 Harness 刷新的 CurrentTimelineView，再提交依赖最新稳定 ID 的原子编辑。"
	data := map[string]any{
		"dependency_requires_observation": true,
		"current_timeline_unchanged":      true,
	}
	if targetClipID != "" {
		data["timeline_clip_id"] = targetClipID
	}
	if decision == atomicEditUnobservedTimelineCoordinate {
		observation = "前一个原子编辑已改变时间线坐标，本条 assistant 消息不能继续使用尚未重新观察的时间线帧。"
		recovery = "等待当前工具消息全部返回；下一次 provider 调用读取 Harness 刷新的 CurrentTimelineView，再提交依赖最新帧范围的原子编辑。稳定 timeline_clip_id 或 asset_id + source range 不受此限制。"
		data["coordinate_dependency"] = "timeline_frames_after_prior_edit"
	}
	return rushestools.ToolFailure(
		rushestools.StatusFailed,
		observation,
		rushestools.ErrCodeStaleTarget,
		recovery,
		data,
	)
}
