"""Stable public contracts for Rushes."""

from .annotation import (
    AnnotationClip,
    AnnotationDocument,
    AnnotationExtensions,
    AnnotationGenerator,
    AudioMusicExtension,
    AudioSpeechExtension,
    CommerceProductExtension,
    EditingAffordanceExtension,
    QualityEvent,
    TextOcrExtension,
    VisionBasicExtension,
    VisionCompositionExtension,
)
from .asset import AssetFailure, AssetKind, AssetProbe, AssetRecord, AssetSource, StorageMode
from .candidate import (
    Candidate,
    CandidatePack,
    CandidatePackSnapshot,
    CandidateScore,
    CandidateSlot,
)
from .case import (
    AudioMode,
    AudioPlan,
    BgmPostprocessPlan,
    Brief,
    CaseState,
    CutPlan,
    CutPlanSlot,
    LastError,
    PostprocessPlan,
    RemovedRange,
    RunningJobRef,
    SubtitlePostprocessPlan,
)
from .costs import ProviderCall
from .decision import Decision, DecisionAnswer, DecisionOption, PendingToolCall
from .events import (
    EVENT_CLASSES,
    EVENT_UNION,
    DomainEvent,
    DomainEventBase,
    EventName,
    event_registry,
)
from .interaction import InteractionKind, InteractionOption, StructuredInteractionEvent
from .jobs import Job, JobError, JobKind, JobStatus
from .memory import Memory, MemoryCandidate
from .patch import (
    AddBgmOp,
    AdjustGainOp,
    AllRange,
    ClipIdsRange,
    DeleteRangeOp,
    EditSubtitleTextOp,
    GenerateSubtitlesOp,
    InsertCandidateOp,
    PatchTimeRange,
    RemoveTrackClipsOp,
    ReorderBlocksOp,
    ReplaceClipOp,
    ResolvedRange,
    ResolvedTimelinePatch,
    SetPlaybackRateOp,
    SetSubtitleStyleOp,
    TimelinePatchOp,
    TimelinePatchReference,
    TimelinePatchRequest,
    TimeRangeSec,
    TrimClipOp,
)
from .project import ProjectAssetLink, ProjectDefaults, ProjectState
from .provider import ProviderCapability, ProviderDescriptor, ProviderError, ProviderResult
from .subtitle import SubtitleBinding, SubtitleClip, SubtitleStyleTemplate
from .timeline import (
    TimelineMediaClip,
    TimelineState,
    TimelineTrack,
    TimelineValidationReport,
    TrackId,
)
from .tool import PatchOpSpec, ToolSpec
from .tool_result import ToolArtifact, ToolError, ToolResult
from .transcript import (
    TranscriptDocument,
    TranscriptUtterance,
    TranscriptWord,
    VadSegment,
)
from .workspace import WorkspaceConfig, WorkspaceDefaults, WorkspaceProjectRef

__version__: str = "0.1.0"

__all__ = [
    "EVENT_CLASSES",
    "EVENT_UNION",
    "AddBgmOp",
    "AdjustGainOp",
    "AllRange",
    "AnnotationClip",
    "AnnotationDocument",
    "AnnotationExtensions",
    "AnnotationGenerator",
    "AssetFailure",
    "AssetKind",
    "AssetProbe",
    "AssetRecord",
    "AssetSource",
    "AudioMode",
    "AudioMusicExtension",
    "AudioPlan",
    "AudioSpeechExtension",
    "BgmPostprocessPlan",
    "Brief",
    "Candidate",
    "CandidatePack",
    "CandidatePackSnapshot",
    "CandidateScore",
    "CandidateSlot",
    "CaseState",
    "ClipIdsRange",
    "CommerceProductExtension",
    "CutPlan",
    "CutPlanSlot",
    "Decision",
    "DecisionAnswer",
    "DecisionOption",
    "DeleteRangeOp",
    "DomainEvent",
    "DomainEventBase",
    "EditSubtitleTextOp",
    "EditingAffordanceExtension",
    "EventName",
    "GenerateSubtitlesOp",
    "InsertCandidateOp",
    "InteractionKind",
    "InteractionOption",
    "Job",
    "JobError",
    "JobKind",
    "JobStatus",
    "LastError",
    "Memory",
    "MemoryCandidate",
    "PatchOpSpec",
    "PatchTimeRange",
    "PendingToolCall",
    "PostprocessPlan",
    "ProjectAssetLink",
    "ProjectDefaults",
    "ProjectState",
    "ProviderCall",
    "ProviderCapability",
    "ProviderDescriptor",
    "ProviderError",
    "ProviderResult",
    "QualityEvent",
    "RemoveTrackClipsOp",
    "RemovedRange",
    "ReorderBlocksOp",
    "ReplaceClipOp",
    "ResolvedRange",
    "ResolvedTimelinePatch",
    "RunningJobRef",
    "SetPlaybackRateOp",
    "SetSubtitleStyleOp",
    "StorageMode",
    "StructuredInteractionEvent",
    "SubtitleBinding",
    "SubtitleClip",
    "SubtitlePostprocessPlan",
    "SubtitleStyleTemplate",
    "TextOcrExtension",
    "TimeRangeSec",
    "TimelineMediaClip",
    "TimelinePatchOp",
    "TimelinePatchReference",
    "TimelinePatchRequest",
    "TimelineState",
    "TimelineTrack",
    "TimelineValidationReport",
    "ToolArtifact",
    "ToolError",
    "ToolResult",
    "ToolSpec",
    "TrackId",
    "TranscriptDocument",
    "TranscriptUtterance",
    "TranscriptWord",
    "TrimClipOp",
    "VadSegment",
    "VisionBasicExtension",
    "VisionCompositionExtension",
    "WorkspaceConfig",
    "WorkspaceDefaults",
    "WorkspaceProjectRef",
    "__version__",
    "event_registry",
]
